### ISSUE TITLE
OS X Notifications

### ISSUE THREAD

**Issue by nesl247** [moul/irccloud-desktop-app#3]
I'm assuming it's coming at some point, but just in case, I figured I'd request it here.

**Comment by moul** [comment]
Hi @nesl247, I think it's a built-in feature of node-webkit-builder

Here is a notification I got on OS X without tuning anything
![](https://www.dropbox.com/s/4swgfx00e8ix7ro/Screenshot%202015-05-02%2016.27.26.png?dl=1)

Let me know :)

**Comment by nesl247** [comment]
I just tested it again, and notifications are definitely not working. I assumed they would since IRC Cloud isn't showing up in System Preferences -> Notifications.

**Comment by nesl247** [comment]
So I did get it to work. It started working after I executed `window.location.reload()` in the dev tools.
