### ISSUE TITLE
Make links clickable

### ISSUE THREAD

**Issue by nesl247** [moul/irccloud-desktop-app#4]
Currently clicking a link does not do anything. One cannot also right click and get a menu to be able to "Copy Link".

**Comment by moul** [comment]
Thanks for reporting, I will manage to get it working :)

**Comment by moul** [comment]
I just fixed your issue, we can now open links.

I had to switch from a html webview to an iframe, and it brokes the loading of my css for template, but for now, I consider your issue more important than the black skin.
I created a new issue (#5) to re-enable the custom template

**Comment by nesl247** [comment]
Thanks!
