### ISSUE TITLE
Use custom template

### ISSUE THREAD

**Issue by moul** [moul/irccloud-desktop-app#5]
Feature broken with #4

**Comment by nesl247** [comment]
Try this:

```
webview.addEventListener('newwindow', function(e) {
  window.open(e.targetUrl);
});
```

Basically you need to listen to each `newwindow` event and let Chrome's webview know you want to allow it to be clicked.

**Comment by moul** [comment]
It worked when I was using webviews,
but I needed to switch back to iframes to handle clickable links

Clickable links raised an "A new window was blocked" exception

Hum, maybe we can tell node-webkit to don't care about this security feature and switch back again to webviews :) I will check this

Another option would be to stay with iframe, but add a hook on load commit for each pages

**Comment by nesl247** [comment]
What I had meant was to try switching back to webviews, and then looking into injecting in the JS I posted. I think that might solve the links being blocked, at least according to an hour worth of googling.

**Comment by moul** [comment]
It works, thx ! <3
